name: Main Branch Build & Deploy

# Parameters
env:
  DOCKER_REGISTRY: docker.io
  DASHBOARD_APP_IMAGE: mlnative/hono-react-dashboard
  API_APP_IMAGE: mlnative/hono-react-api

permissions:
  packages: write
  id-token: write
  contents: write
on:
  push:
    branches:
      - main

jobs:
  lint-typecheck:
    uses: ./.github/workflows/lint-typecheck.yml

  release:
    name: Semantic Release
    needs: lint-typecheck
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.release.outputs.new_release_version }}
      new_release_published: ${{ steps.release.outputs.new_release_published }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: bun install

      - name: Semantic release
        id: release
        uses: cycjimmy/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #
  # build-dashboard:
  #   uses: ./.github/workflows/build-docker.yml
  #   with:
  #     dockerfile: apps/dashboard/Dockerfile
  #     registry: ${{ env.DOCKER_REGISTRY }}
  #     image_name: ${{ env.DASHBOARD_APP_IMAGE }}
  #     image_tag: ${{ needs.release.outputs.new_release_version }}
  #   secrets: inherit
  #
  # build-api:
  #   uses: ./.github/workflows/build-docker.yml
  #   with:
  #     dockerfile: apps/api/Dockerfile
  #     registry: ${{ env.DOCKER_REGISTRY }}
  #     image_name: ${{ env.API_APP_IMAGE }}
  #     image_tag: ${{ needs.release.outputs.new_release_version }}
  #   secrets: inherit
